import Image from "next/image";
import { CodeBlock } from "@/components/code-block";
import { ProofGallery } from "@/components/proof-gallery";
import { Breadcrumbs, FaqList, PrimaryLink, SectionHeader } from "@/components/page-elements";
import { JsonLd } from "@/components/json-ld";
import { StockVisual } from "@/components/stock-visual";
import { websitePreviews, searchConsoleProof } from "@/lib/assets";
import { SERVICES, SITE } from "@/lib/site";
import { STOCK_IMAGES } from "@/lib/stock-images";
import { breadcrumbSchema, buildMetadata, faqSchema, serviceSchema } from "@/lib/seo";

const service = SERVICES["seo-websites"];
export const metadata = buildMetadata({ title: "Custom SEO, AEO and GEO Websites", description: service.answer, path: "/seo-websites", image: STOCK_IMAGES.seoStructure.src, imageAlt: STOCK_IMAGES.seoStructure.alt });

export default function SeoWebsitesPage() {
  return <>
    <JsonLd data={[serviceSchema(service), breadcrumbSchema([{ name: "Home", path: "/" }, { name: service.navLabel, path: "/seo-websites" }]), faqSchema(service.faqs)]} />
    <section className="service-hero section-dark"><div className="section-shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: service.navLabel }]} /><div className="service-hero-grid"><div><p className="eyebrow">Custom-coded visibility foundation</p><h1>Custom SEO, AEO and GEO websites.</h1><p className="lede">{service.answer}</p><div className="price-lockup"><strong>{service.price}</strong><span>{service.cadence}</span></div><PrimaryLink href={SITE.calendly}>Book the website package</PrimaryLink></div><CodeBlock /></div></div></section>
    <section className="section section-paper"><div className="section-shell split-layout"><div><SectionHeader question="What does client-owned custom code change?" answer="The repository, deployment, and domain stay in accounts you control. The site is built in Next.js instead of being trapped inside a page-builder subscription." /><ol className="process-list">{service.process.map((step,index)=><li key={step.title}><b>0{index+1}</b><span><strong>{step.title}</strong><br />{step.body}</span></li>)}</ol></div><aside className="inclusion-sheet inclusion-sheet--visual"><StockVisual image={STOCK_IMAGES.seoFoundation}/><h2>What does the website package include?</h2><ul>{service.includes.map(item=><li key={item}>{item}</li>)}</ul><div><strong>Not included</strong><p>{service.exclusions.join(" · ")}</p></div></aside></div></section>
    <section className="section section-white"><div className="section-shell split-layout stock-split"><div><SectionHeader question="What does technical SEO organize?" answer="Technical SEO gives search engines a consistent path through the site while keeping the customer experience readable and fast."/><p>CEOTurbo connects crawlable page structure, internal links, canonicals, sitemaps, schema, responsive media, and performance checks. None of those elements replaces a useful offer or original proof.</p></div><StockVisual image={STOCK_IMAGES.seoStructure}/></div></section>
    <section className="section section-paper"><div className="section-shell"><SectionHeader question="How do metadata and source code support discovery?" answer="Every indexable page needs metadata that matches its visible purpose, plus implementation that search and social systems can actually read."/><div className="stock-media-grid"><StockVisual image={STOCK_IMAGES.metadata}/><StockVisual image={STOCK_IMAGES.metadataCode}/></div></div></section>
    <section className="section section-white"><div className="section-shell"><SectionHeader question="How does a website become easier to find and evaluate?" answer="A clear domain destination, answer-first page content, and ongoing performance measurement help customers and search systems understand the business."/><div className="stock-media-grid stock-media-grid--three"><StockVisual image={STOCK_IMAGES.seoPerformance}/><StockVisual image={STOCK_IMAGES.websiteDiscovery}/><StockVisual image={STOCK_IMAGES.seoGrowth}/></div></div></section>
    <section className="section section-paper"><div className="section-shell"><SectionHeader question="What do the finished websites look like?" answer={`All ${websitePreviews.length} website previews are shown below without cropping. Select an image to visit the live website, or use the full-size preview control to inspect the screenshot.`} /><ProofGallery items={websitePreviews} label="All CEOTurbo website previews" /></div></section>
    <section className="section section-white"><div className="section-shell split-layout stock-split"><div><p className="eyebrow">Historical Search Console example</p><h2>What should search measurement look like after launch?</h2><p>The supplied twelve-month screenshot shows 83 clicks, 3.34K impressions, 2.5% CTR, and a 25.4 average position. Search outcomes differ by market, site history, demand, competition, and ongoing work.</p><StockVisual image={STOCK_IMAGES.searchConsole}/></div><a className="search-proof-link" href={searchConsoleProof.src} target="_blank" rel="noreferrer"><Image src={searchConsoleProof.src} alt={searchConsoleProof.alt} width={searchConsoleProof.width} height={searchConsoleProof.height} sizes="(max-width:820px) 92vw, 420px" /></a></div></section>
    <section className="section section-paper"><div className="section-shell narrow"><SectionHeader question="What should you ask about the website package?" /><FaqList faqs={service.faqs} /></div></section>
    <section className="final-cta section-dark"><div className="section-shell"><h2>Ready to own the code and understand the handoff?</h2><p>Book a scope call before purchasing. We will confirm pages, proof, eligibility, and timeline.</p><PrimaryLink href={SITE.calendly}>Book the website call</PrimaryLink></div></section>
  </>;
}
